Spring Cloud Gateway provee una forma simple de redirigir peticiones a diversas APIs tomando en cuenta aspectos de seguridad, monitoreo y resilencia.

Al combinarse con Spring Security 5.2+ y un proveedor OpenID tal como Keycloak, uno puede tener rápidamente una configuración  de un gateway seguro para el acceso servicios protegidos mediante OAuth2.

== Implementación

El ejemplo modela un sitio web de viajes implementado como un gateway conectado a dos servicios, uno de vuelos y otro de hoteles.

=== Keycloak

En este punto ya debemos tener configurado y listo nuestro servidor Keycloak.

=== Gateway

El gateway es mínimo en cuanto a dependencias, código y configuración.

==== Dependencias
1. La autenticación con el proveedor OpenID es manejada por `org.springframework.boot:spring-boot-starter-oauth2-client`
2. La funcionalidad del gateway es proporcionada por `org.springframework.cloud:spring-cloud-starter-gateway`
3. El reenvío de los tokens a los servicios protegidos lo proporciona `org.springframework.cloud:spring-cloud-security`

==== Code
Además de la anotación `@SpringBootApplication` básicamente lo que necesitamos es esto:
[source,java]
----
@Bean
public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http,
    ReactiveClientRegistrationRepository clientRegistrationRepository) {
  
  // Se autentica con el proveedor OpenID
  http.oauth2Login();
  
  // Se hace el logout con el proveedor OpenID
  http.logout(logout -> logout.logoutSuccessHandler(new OidcClientInitiatedServerLogoutSuccessHandler(clientRegistrationRepository)));
  
  // Requier autenticación para todas las peticiones
  http.authorizeExchange().anyExchange().authenticated();
  
  // Allow showing /home within a frame
  http.headers().frameOptions().mode(Mode.SAMEORIGIN);
  
  // Disable CSRF in the gateway to prevent conflicts with proxied service CSRF
  http.csrf().disable();
  return http.build();
}
----
==== Configuration
Esta es la parte que integra Spring Security con Keycloak.
[source,yaml]
----
server:
  port: 9090

spring:
  application:
    name: travel-spring-cloud-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/jvmmx
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-cloud-gateway-client
            client-secret: 81a0dfd8-49b7-4c4b-8a8d-92f1ed9636b1
----
Esta otra es la que define las rutas y los servicios-
[source,yaml]
----
  cloud:
    gateway:
      default-filters:
      - TokenRelay

      routes:
      - id: flights-service
        uri: http://localhost:8081/flights
        predicates:
        - Path=/flights/**

      - id: hotels-service
        uri: http://localhost:8082/hotels
        predicates:
        - Path=/hotels/**
----

`TokenRelay` activa el `TokenRelayGatewayFilterFactory`, el cual agrega `Bearer` token a las peticiones recibidas por el gateway.

=== Servicios
Los servicios ofrecidos sólo difieren por el nombre, "flights" y "hotels", realmente tienen muy poco código implementado, la idea básicamente es tener un par de servicios que demuestren la integración con Spring Cloud Gateway.

==== Dependencias
Para los dos servicios se agrega esta dependencia `org.springframework.boot:spring-boot-starter-oauth2-resource-server` a los proyectos la cual a su vez integra estas 3 dependencias.

1. La validación de los tokens con el proveedor OpenID es manejada por `org.springframework.security:spring-security-oauth2-resource-server`
2. Decodificación de los JSON Web Tokens es realizada por `org.springframework.security:spring-security-oauth2-jose`
3. Personalización del manejo de los tokens requiere `org.springframework.security:spring-security-config`

==== Código de los servicios
Lo principal es el código para el manejo de los tokens, nos tenemos que asegurar que los tokens son decodificados y checados apropiadamente en cada petición.
[source,java]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    
    // Validación de los tokens a través del proveedor OpenID
    http.oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter());
    
    // Se requiere autencicación para todas las peticiones
    http.authorizeRequests().anyRequest().authenticated();
    
    // Permite mostrar páginas en un frame html
    http.headers().frameOptions().sameOrigin();
  }

  ...
}
----

También se extraen algunos datos que vienen en el token generado por Keycloak
Este paso es opcional y puede variar según el proveedor de OpenID y cómo se haga el mapeo de roles
[source,java]
----
private JwtAuthenticationConverter jwtAuthenticationConverter() {
  JwtAuthenticationConverter converter = new JwtAuthenticationConverter();
  
  //Convierte realm_access.roles para usarlos en decisiones de acceso a recursos
  converter.setJwtGrantedAuthoritiesConverter(new KeycloakRealmRoleConverter());
  return converter;
}

[...]

class KeycloakRealmRoleConverter implements Converter<Jwt, Collection<GrantedAuthority>> {
  @Override
  public Collection<GrantedAuthority> convert(Jwt jwt) {
    final Map<String, Object> realmAccess = (Map<String, Object>) jwt.getClaims().get("realm_access");
    return ((List<String>) realmAccess.get("roles")).stream()
      .map(roleName -> "ROLE_" + roleName)
      .map(SimpleGrantedAuthority::new)
      .collect(Collectors.toList());
  }
}
----

Finalmente extraemos el `preferred_name` del token.
[source,java]
----
@Bean
public JwtDecoder jwtDecoderByIssuerUri(OAuth2ResourceServerProperties properties) {
  String issuerUri = properties.getJwt().getIssuerUri();
  NimbusJwtDecoder jwtDecoder = (NimbusJwtDecoder) JwtDecoders.fromIssuerLocation(issuerUri);
  
  // Use preferred_username from claims as authentication name, instead of UUID subject
  jwtDecoder.setClaimSetConverter(new UsernameSubClaimAdapter());
  return jwtDecoder;
}

[...]

class UsernameSubClaimAdapter implements Converter<Map<String, Object>, Map<String, Object>> {

  private final MappedJwtClaimSetConverter delegate = MappedJwtClaimSetConverter.withDefaults(Collections.emptyMap());

  @Override
  public Map<String, Object> convert(Map<String, Object> claims) {
    Map<String, Object> convertedClaims = this.delegate.convert(claims);
    String username = (String) convertedClaims.get("preferred_username");
    convertedClaims.put("sub", username);
    return convertedClaims;
  }

}
----

==== Configuración
La parte de configuración de los servicios es muy parecida.

Los servicios se inician en puertos diferentes y el correspondiente context-path que se haya configurado en el gateway.

Es importante apuntar `issuer-uri` a la misma URL del realm de Keycloak para asegurar que los tokens son decodificados y validados apropiadamente.

[source,yaml]
----
server:
  port: 8081
  servlet:
    context-path: /flights/
spring:
  application:
    name: flights-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/jvmmx
----


[source,yaml]
----
server:
  port: 8082
  servlet:
    context-path: /hotels/
spring:
  application:
    name: hotels-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/jvmmx
----

== Conclusion
With all this in place we have the basics of a functioning gateway.
It redirects users to Keycloak for authentication, while hiding the JSON Web Token from the user.
Any proxied requests to resource servers are enriched with the appropriate user `access_token`, which is verified and converted into an `JwtAuthenticationToken` for use in access decisions.





== Referencias
https://cloud.spring.io/spring-cloud-gateway/reference/html/[Spring Cloud Gateway] +
https://docs.spring.io/spring-security/site/docs/5.2.x/reference/htmlsingle/#oauth2login[OAuth 2.0 Login] +
https://docs.spring.io/spring-security/site/docs/5.2.x/reference/htmlsingle/#oauth2resourceserver[OAuth 2.0 Resource Server] +
https://cloud.spring.io/spring-cloud-static/spring-cloud-security/2.2.0.M3/reference/html/[Spring Cloud Security] +
